---
###################################################
##########           HOSTNAME           ###########
###################################################

- name: "[Hostname] Changes"
  hostname:
    name: "{{ inventory_hostname }}"
  when: ansible_fqdn != ansible_ssh_host

- name: "[Hosts] Set all IPv4"
  template:
    src: "etc/hosts.j2"
    dest: "/etc/hosts"
    owner: root
    group: root
    mode: 0644
  when: ansible_fqdn != ansible_ssh_host

###################################################
##########       INSTALL PACKAGES       ###########
###################################################

- name: "[APT] Update & Upgrade"
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: "[APT] Install packages"
  apt:
    name: "{{ debian_packages }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: "[Script] Customs Bin"
  copy:
    src: "usr/local/bin/"
    dest: "/usr/local/bin/"
    owner: root
    group: root
    mode: 0755
    directory_mode: yes

###################################################
##########           NETWORK            ###########
###################################################

- name: "[Network] Disable IPv6"
  template:
    src: "etc/sysctl.d/70-disable-ipv6.conf.j2"
    dest: "/etc/sysctl.d/70-disable-ipv6.conf"
    owner: root
    group: root
    mode: 0644
  notify: "reload sysctl temp"

###################################################
##########             NTP              ###########
###################################################

- name: "[Time] Set Timezone Paris"
  timezone:
    name: Europe/Paris

- name: "[Time] NTP Configuration"
  template:
    src: "etc/ntp.conf.j2"
    dest: "/etc/ntp.conf"
    owner: root
    group: root
    mode: 0644
  notify: "restart ntp"

###################################################
##########             SSH              ###########
###################################################

- name: "[SSH] SSH Configuration"
  template:
    src: "etc/ssh/sshd.conf.j2"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: 0644
    validate: /usr/sbin/sshd -t -f %s
  notify: "restart ssh"

- name: "[MOTD] Ensure default is absent"
  file:
    path: "/etc/update-motd.d/10-uname"
    state: absent

- name: "[MOTD] Script"
  template:
    src: "etc/motd.j2"
    dest: "/etc/motd"
    owner: root
    group: root
    mode: 0444

###################################################
##########           FAIL2BAN           ###########
###################################################

- name: "[F2B] Fail2Ban Configuration"
  template:
    src: "etc/fail2ban/fail2ban.conf.j2"
    dest: "/etc/fail2ban/fail2ban.conf"
    owner: root
    group: root
    mode: 0644
  notify: "restart fail2ban"

- name: "[F2B] Jails Configuration"
  template:
    src: "etc/fail2ban/jail.d/default.conf.j2"
    dest: "/etc/fail2ban/jail.d/default.conf"
    owner: root
    group: root
    mode: 0644
  notify: "restart fail2ban"

###################################################
##########           IPTABLES           ###########
###################################################

- name: "[IPTABLES] Rules"
  template:
    src: "etc/iptables/rules.v4.j2"
    dest: "/etc/iptables/rules.v4"
    owner: root
    group: root
    mode: 0644
    validate: "iptables-restore --test %s"
  notify: "restore iptables"

###################################################

- name: "[ALL] Flush handlers"
  meta: flush_handlers
