---
debian_packages:
  - apt-transport-https
  - curl
  - wget
  - tree
  - mlocate
  - vim
  - htop
  - bc
  - ntp
  - ntpstat
  - net-tools
  - fail2ban
  - iptables-persistent

ntp_servers:
  - "0.fr.pool.ntp.org iburst"
  - "1.fr.pool.ntp.org iburst"
  - "2.fr.pool.ntp.org iburst"
  - "3.fr.pool.ntp.org iburst"

ssh_port: 22

ip_certified:
  - "xxx.xxx.xxx.xxx"

ip_monitoring:
  - "xxx.xxx.xxx.xxx"

motd_info:
  - " FQDN:    ": "{{ ansible_fqdn }}"
  - " Distro:  ": "{{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }} {{ ansible_architecture }}"
  - " CPUs:    ": "{{ ansible_processor_vcpus }}"
  - " RAM:     ": "{{ (ansible_memtotal_mb / 1000) | round(1) }}GB"
  - " IPs:     ": "{{ ansible_all_ipv4_addresses | join(' ') }}"
